name = "WhatCord"
license = "MIT"
licenselink = "https://github.com/crisomalke/bookworm-light/blob/master/LICENSE"
description = "WhatCord is the place for all of your questions related the discord. We provide answers of many questions and resources with the blog."
homepage = "https://github.com/gethugothemes/bookworm-light/"
demosite = "https://demo.gethugothemes.com/bookworm-light/"
tags = ['blog', 'light', 'bootstrap', 'responsive', 'contact-form']
features = ['responsive']
min_version = "0.80.0"

[author]
name = "gethugothemes"
homepage = "https://gethugothemes.com/"
